import type { Metadata } from "next";
import { Lato } from "next/font/google";

import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Notification from "@/components/Notification";

import "./globals.css";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <Notification />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
