import type { Metadata } from "next";
import { Lato } from "next/font/google";

import { Footer, Header, Notification } from "@/components";

import "./globals.css";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`h-full color-[var(--primary-text-color)] ${lato.className}`}
      >
        <Notification />
        <div className="overflow-x-clip flex flex-col justify-between min-h-[100%]">
          <Header />
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
